name: todo-list-manager
  
services:
  db:
    container_name: list-db  
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD} #interpolacion necesaria porque queria usar MYSQL_USER acá además de en la APP.
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    networks:
      - todo-list-net
    volumes:
      - list-db:/var/lib/mysql
    restart: always
    healthcheck:
      test: mysql --user=root --password=${MYSQL_ROOT_PASSWORD} --execute="SHOW DATABASES;"
      interval: 1s

    
  app:
    container_name: list-app
    image: isaiaslafon/todo-list-manager:v0.2
    environment:
      - MYSQL_HOST=${MYSQL_HOST}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DB=${MYSQL_DB}
    depends_on:
      db:
        condition: service_healthy
    networks:
      - todo-list-net
    ports:
      - 8080:3000
    restart: always


networks:
  todo-list-net:
     driver: bridge

volumes:
  list-db:
